import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const url=Deno.env.get("SUPABASE_URL")||"";
const service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const db=createClient(url||"http://127.0.0.1",service||"missing",{auth:{persistSession:false}});
const cors={"content-type":"application/json","access-control-allow-origin":"*","access-control-allow-headers":"content-type,authorization"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
const norm=(v:unknown)=>String(v??"").normalize("NFKC").trim();
const campusKey=(v:unknown)=>{const s=norm(v);if(s.includes("神領"))return "神領";if(s.includes("大手"))return "大手";return s};
const campusOK=(teacher:unknown,student:unknown)=>norm(teacher).split("・").map(campusKey).includes(campusKey(student));
async function hash(raw:string){const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(raw));return [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function teacherSession(token:string){if(!token)throw new Error("AUTH_REQUIRED");const tokenHash=await hash(token),now=new Date().toISOString();const {data,error}=await db.from("foresta_v3_sessions").select("profile,expires_at").eq("token_hash",tokenHash).gt("expires_at",now).maybeSingle();if(error)throw error;if(!data)throw new Error("AUTH_REQUIRED");const profile=(data.profile?.session||data.profile||{}) as Record<string,unknown>;if(String(profile.role||"")!=="teacher")throw new Error("FORBIDDEN");return profile}
async function dashboard(studentId:string){const {data,error}=await db.from("foresta_v3_snapshots").select("payload,updated_at").eq("student_id",studentId).eq("view","getStudentDashboard").eq("subject","").maybeSingle();if(error)throw error;if(!data)throw new Error("SNAPSHOT_NOT_READY");return data}
async function adjustment(profile:Record<string,unknown>,studentId:string,subject:string){const dash=await dashboard(studentId),student=dash.payload?.student||{};if(!campusOK(profile.campus,student.campus))throw new Error("FORBIDDEN");const active=(Array.isArray(dash.payload?.homework)?dash.payload.homework:[]).filter((item:Record<string,unknown>)=>norm(item.subject)===subject&&String(item.source||"")==="teacher"&&!item.archived);const {data:overrides,error}=await db.from("foresta_v3_homework_overrides").select("homework_id,item,updated_at").eq("student_id",studentId).eq("subject",subject).eq("hidden",true);if(error)throw error;const map=new Map<string,Record<string,unknown>>();for(const item of active)map.set(String(item.homeworkId||""),{...item,adjustedHidden:false});for(const row of overrides||[]){const item=(row.item||{}) as Record<string,unknown>;if(item.homeworkId)map.set(String(item.homeworkId),{...item,adjustedHidden:true})}const homework=[...map.values()].sort((a,b)=>new Date(String(b.createdAt||b.recommendedDueDate||0)).getTime()-new Date(String(a.createdAt||a.recommendedDueDate||0)).getTime());return {ok:true,student,subject,homework,snapshotUpdatedAt:dash.updated_at}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{headers:cors});try{const body=await req.json() as Record<string,unknown>,profile=await teacherSession(String(body.token||""));const studentId=norm(body.studentId),subject=norm(body.subject);if(!studentId||!subject)throw new Error("INVALID_VALUE");if(String(body.action||"")==="getNextHomeworkAdjustment")return json(await adjustment(profile,studentId,subject));if(String(body.action||"")==="adjustHomework"){const before=await adjustment(profile,studentId,subject),allowed=new Set((before.homework||[]).map((item:Record<string,unknown>)=>String(item.homeworkId||"")));const allIds=[...new Set((Array.isArray(body.homeworkIds)?body.homeworkIds:[]).map(String).filter(Boolean))],keepIds=[...new Set((Array.isArray(body.keepHomeworkIds)?body.keepHomeworkIds:[]).map(String).filter(Boolean))];if(allIds.some(id=>!allowed.has(id))||keepIds.some(id=>!allowed.has(id)))throw new Error("FORBIDDEN");const {data,error}=await db.rpc("foresta_v3_adjust_homework_visibility",{p_student_id:studentId,p_subject:subject,p_all_ids:allIds,p_keep_ids:keepIds,p_actor_id:String(profile.loginId||"")});if(error)throw error;const after=await adjustment(profile,studentId,subject);return json({ok:true,...(data||{}),hiddenIds:(after.homework||[]).filter((item:Record<string,unknown>)=>item.adjustedHidden).map((item:Record<string,unknown>)=>String(item.homeworkId||"")),homework:after.homework})}return json({ok:false,message:"INVALID_ACTION"},400)}catch(error){const message=error instanceof Error?error.message:String(error),status=message==="AUTH_REQUIRED"?401:message==="FORBIDDEN"?403:["INVALID_VALUE","INVALID_ACTION"].includes(message)?400:message==="SNAPSHOT_NOT_READY"?503:500;return json({ok:false,message},status)}});
