import assert from "node:assert/strict";
import fs from "node:fs";
const app=fs.readFileSync(new URL("../app.js",import.meta.url),"utf8");
const elem=fs.readFileSync(new URL("../elementary-supabase.js",import.meta.url),"utf8");
const css=fs.readFileSync(new URL("../elementary-supabase.css",import.meta.url),"utf8");
const buttons=fs.readFileSync(new URL("../v3-homework-ui-fix.js",import.meta.url),"utf8");
assert.ok(app.includes('単元（章）'));
assert.ok(!app.includes('大きな単元（章）'));
assert.ok(!app.includes('宿題・進行表を訂正'));
assert.ok(app.includes('id="correctElementaryLesson" class="ghostBtn homeworkReviewBtn">次回の宿題を確認'));
assert.ok(app.includes('onsubmit="return false"'));
assert.ok(!app.includes('bindElementaryTopTestEntry(data,studentId,rows);'));
assert.ok(!app.includes('function bindElementaryTopTestEntry'));
assert.ok(!app.includes('function openElementaryUnitTestForm'));
assert.ok(!app.includes('querySelectorAll(".elementaryUnitTestButton")'));
assert.ok(!app.includes('querySelectorAll(".elementarySchoolPosition").forEach'));
assert.ok(!app.includes('querySelectorAll(".elementaryTestEntry").forEach'));
assert.ok(app.includes('表面の点数<input id="elementaryTopTestScore"'));
assert.ok(app.includes('value="50" required'));
assert.ok(app.includes('表面の満点<input id="elementaryTopTestMax"'));
assert.ok(app.includes('裏面の点数<input id="elementaryTopTestBackScore"'));
assert.ok(app.includes('value="30" required'));
assert.ok(app.includes('裏面の満点<input id="elementaryTopTestBackMax"'));
assert.ok(elem.includes('const otherPlaceholder = normalized === "国語" ? "教科書漢字ドリルなど"'));
assert.ok(elem.includes('placeholder="${esc(otherPlaceholder)}"'));
assert.ok(elem.includes("lessonSubjectSelect?.addEventListener('change', syncCustomHomeworkSubject)"));
assert.ok(elem.includes('memo: text, assignedDate: todayJst()'));
assert.ok(elem.includes('<legend class="hidden">表面</legend>'));
assert.ok(elem.includes('表面の点数<input id="eTestScore"'));
assert.ok(elem.includes('value="50" autofocus'));
assert.ok(elem.includes('<legend class="hidden">裏面</legend>'));
assert.ok(elem.includes('裏面の点数<input id="eTestBackScore"'));
assert.ok(elem.includes('value="30">'));
assert.ok(elem.includes('scoreEl.value = "50"'));
assert.ok(elem.includes('backScoreEl.value = "30"'));
assert.ok(!elem.includes('<legend>表面</legend>'));
assert.ok(!elem.includes('<legend>裏面</legend>'));
assert.ok(elem.includes('if (normalized === "国語") return loadJapaneseProgressions(grade);'));
assert.ok(elem.includes('const selectedTypes = normalized === "国語" ? ["TODAY_REDO"] : ["TRY_REDO", "EXERCISE"]'));
assert.ok(elem.includes('selectedTypes: [], other: ""'));
assert.ok(elem.includes('saveSchoolPosition'));
assert.ok(elem.includes('saveUnitTest'));
assert.ok(elem.includes('const chapterLabel = /^\\d+$/u.test(raw)'));
assert.ok(css.includes('.elementaryOtherHomework::placeholder'));
assert.ok(buttons.includes('function createElementaryReviewButton'));
assert.ok(buttons.includes('button.textContent = "次回の宿題を確認"'));
assert.ok(elem.includes('id="elementaryReviewHomework"'));
assert.ok(elem.includes('foresta:open-elementary-homework'));
assert.ok(!elem.includes('次回宿題を確認・調整'));
assert.ok(buttons.includes('進行表を開く'));
assert.ok(!buttons.includes('宿題・進行表を訂正'));
assert.match(app,/replace\(\/\[ァ-ヶ\]\/g/);
assert.match(app,/student\.reading/);
assert.match(app,/student\.romaji/);
assert.ok(app.includes('FAST_RUNTIME_WRITE_ACTIONS.has(action) ? "高速保存中…" : "高速読込中…"'));
console.log("elementary specification audit: ok");
