import assert from "node:assert/strict";
import fs from "node:fs";
import vm from "node:vm";

const source = fs.readFileSync(new URL("../apps-script/Code.gs", import.meta.url), "utf8");
const context = vm.createContext({ console, Set, Map, Date, JSON, Math, Number, String, Object, Array, RegExp });
vm.runInContext(source, context, { filename: "Code.gs" });

assert.equal(context.activeStatus_(1), true);
assert.equal(context.activeStatus_("0"), true);
assert.equal(context.activeStatus_(""), false);
assert.equal(context.activeStatus_(2), false);
assert.equal(context.normalizeSchool_(" 南城 中学校 "), "南城中");
assert.equal(context.normalizeGrade_("中学２年"), "中2");
assert.equal(context.kanaFold_("タナカ　太郎"), "たなか太郎");
assert.equal(context.romanizeKana_("カトウ ハナコ"), "katouhanako");
assert.equal(context.romanizeKana_("ヤマモト エイスケ"), "yamamotoeisuke");
assert.match(context.romajiSearchText_("カトウ ハナコ"), /katohanako/);
const masterRow = Array(16).fill("");
masterRow[0] = "S001";
masterRow[1] = "1";
masterRow[4] = "加藤 花子";
masterRow[5] = "カトウ ハナコ";
masterRow[7] = "神領";
masterRow[10] = "中学2年";
masterRow[15] = "南城中学校";
assert.equal(context.studentFromMasterRow_(masterRow).reading, "カトウ ハナコ");
assert.match(context.studentFromMasterRow_(masterRow).romaji, /katouhanako/);
assert.equal(context.studentFromMasterRow_(masterRow).filterCampus, "神領");
assert.equal(context.studentMatchesQuery_(context.studentFromMasterRow_(masterRow), "katou"), true);
assert.equal(context.studentMatchesQuery_(context.studentFromMasterRow_(masterRow), "kato"), true);
assert.equal(context.studentMatchesQuery_(context.studentFromMasterRow_(masterRow), "かとう 中2"), true);
assert.equal(context.omission_("!", 1), true);
assert.equal(context.omission_("!!", 1), true);
assert.equal(context.omission_("!!", 2), true);
assert.equal(context.omission_("!", 2), false);
assert.equal(context.omission_("!!", 3), false);
assert.equal(context.omission_("!", ""), false);
assert.equal(context.publicError_(new Error("LOGIN_FAILED")), "IDまたはパスワードを確認してください。");
assert.deepEqual(Array.from(context.homeworkItemsForUnit_("英語", { unitName: "KEY WORDS TEST", unitNumber: "Key Words TEST" }, ["Try赤×直し", "exercise"])), ["巻末のKeyWordsTestの暗記"]);
assert.deepEqual(Array.from(context.homeworkItemsForUnit_("数学", { unitName: "KEY WORDS TEST", unitNumber: "Key Words TEST" }, ["TRYの赤×直し", "exercise"])), ["巻末のKeyWordsTestの暗記"]);
assert.deepEqual(Array.from(context.homeworkItemsForUnit_("英語", { unitName: "About Me", unitNumber: "Part1" }, ["Try赤×直し", "exercise"])), ["Try赤×直し", "exercise"]);

context.loadSession_ = () => ({ role: "admin", loginId: "ADMIN", permission: 1 });
context.requireAdmin_ = () => ({ role: "admin", loginId: "ADMIN", permission: 1 });
context.getActiveStudent_ = (studentId) => ({ studentId });
const adminProgressAccess = context.authorizeStudentAccess_({ token: "admin-token", adminToken: "admin-token", studentId: "S001" });
assert.equal(adminProgressAccess.session.role, "admin");
assert.equal(adminProgressAccess.student.studentId, "S001");
context.requireAdmin_ = () => { throw new Error("FORBIDDEN"); };
assert.throws(() => context.authorizeStudentAccess_({ token: "admin-token", adminToken: "invalid", studentId: "S001" }), /FORBIDDEN/);

console.log("GAS pure tests: 30 assertions passed");
