import assert from "node:assert/strict";
import fs from "node:fs";

const app = fs.readFileSync(new URL("../app.js", import.meta.url), "utf8");
const gas = fs.readFileSync(new URL("../apps-script/Code.gs", import.meta.url), "utf8");
const styles = fs.readFileSync(new URL("../styles.css", import.meta.url), "utf8");

assert.match(gas, /const reading=text_\(row\[5\]\)/);
assert.match(gas, /student\.reading/);
assert.match(app, /ひらがな・カタカナ/);
assert.match(app, /ひらがな・カタカナ・ローマ字/);
assert.match(app, /katou/);
assert.match(app, /入力すると自動で検索します/);
assert.match(app, /function scheduleStudentSearch/);
assert.match(app, /setTimeout\(\(\) => \{ if \(\$\("studentSearch"\)\) runStudentSearch\(\); \}, 250\)/);
assert.match(app, /\$\("studentSearch"\)\.oninput = scheduleStudentSearch/);
assert.match(app, /\$\("campusFilter"\)\.onchange = scheduleStudentSearch/);
assert.match(app, /\$\("gradeFilter"\)\.onchange = scheduleStudentSearch/);
assert.doesNotMatch(app, /id="searchButton"/);
assert.match(gas, /function romanizeKana_/);
assert.match(gas, /function studentMatchesQuery_/);
assert.match(gas, /studentMatchesQuery_\(student, data\.query\)/);
assert.match(app, /teacherStudentCache/);
assert.match(app, /let data = !force \? state\.teacherStudentCache/);
assert.match(app, /function activateTeacherStudent/);
assert.match(app, /<span>担当講師<\/span>/);
assert.match(app, /id="inputLesson" class="primaryBtn">進行表を開く/);
assert.doesNotMatch(app, /id="viewProgress"/);
assert.doesNotMatch(app, /選択した1単元を学校位置に保存/);
assert.match(app, /class="schoolPinButton/);
assert.match(app, /class="lessonDayToggle/);
assert.match(app, /lessonDates/);
assert.match(gas, /lessonDates: dates\.map/);
assert.match(gas, /recordedDate/);
assert.match(app, /<th>国語<\/th><th>数学<\/th><th>英語<\/th><th>理科<\/th><th>社会<\/th><th>5科<\/th>/);
assert.match(app, /class="card span12 teacherNoticeCard"/);
assert.doesNotMatch(app, /class="studentTabClose"/);
assert.match(app, /function persistTeacherLessonSelection/);
assert.match(app, /function restoreTeacherLessonSelection/);
assert.match(app, /function endTeacherLesson/);
assert.match(app, /function changeTeacherStudent/);
assert.match(app, /studentChangeButton/);
assert.match(app, /生徒を選び直しますか/);
assert.match(app, /lessonEndButton/);
assert.match(app, /授業を終了して、選択中の生徒をすべて閉じますか/);
assert.match(app, /modeIndicator/);
assert.match(app, /🏫 学校 /);
assert.match(styles, /\.schoolPinButton\.active\{[^}]*background:#126fba/);
assert.match(app, /class="scoreCorrectionMini"/);
assert.match(app, /class="progressStudentName"/);
assert.match(app, /class="unitHomeworkGroup"/);
assert.match(app, /unitHomeworkPreset/);
assert.match(app, /homeworkByUnit/);
assert.match(app, /保存しています。画面を閉じずにお待ちください/);
assert.match(app, /button\.textContent = "保存中…"/);
assert.match(gas, /function appendObjects_/);
assert.match(gas, /appendObjects_\('授業実施単元',lessonUnitRows\)/);
assert.match(gas, /appendObjects_\('宿題',homeworkRows\)/);
assert.match(app, /class="teacherSearchGrid"/);
assert.match(styles, /\.teacherSearchGrid\{display:grid;grid-template-columns:minmax\(220px,2fr\) minmax\(100px,1fr\) minmax\(100px,1fr\)/);
assert.match(app, /id="correctLesson"/);
assert.match(app, /function openLessonCorrection/);
assert.match(app, /class="lessonCorrectionItem"/);
assert.match(app, /existingHomeworkByUnit/);
assert.match(app, /correcting \? "updateLessonCorrection" : "saveLesson"/);
assert.doesNotMatch(app, /class="schoolPositionGuide"/);
assert.match(app, /class="schoolLegendControl"/);
assert.match(styles, /\.schoolPinButton\.active\{min-width:0/);
assert.match(gas, /case 'getLessonCorrections': return getLessonCorrections_\(data\)/);
assert.match(gas, /case 'updateLessonCorrection': return updateLessonCorrection_\(data\)/);
assert.match(gas, /function getLessonCorrections_/);
assert.match(gas, /function updateLessonCorrection_/);
assert.match(gas, /replaceRows_\('授業実施単元'/);
assert.match(gas, /replaceRows_\('宿題'/);
assert.match(app, /const orderedSubjects = \[\.\.\.new Set\(\[\.\.\.\(data\.student\.subjects \|\| \[\]\), \.\.\.SUBJECTS\]\)\]/);
assert.match(app, /科目を選択してください/);
assert.match(app, /savedTeacherSubject/);
assert.match(app, /elementaryLessonSubject/);
assert.match(app, /teacherSubjects/);
assert.match(app, /\["英語", "数学"\]\.includes\(options\.subject\) && u\.ctResult/);
assert.match(app, /国語には決まった宿題項目はありません/);
assert.match(app, /その他欄のみ/);
assert.match(gas, /const TRACKED_SUBJECTS = \['国語', '英語', '数学', '理科', '社会'\]/);
assert.match(gas, /\['英語','数学'\]\.indexOf\(subject\)<0\|\|\['◎','〇','×'\]/);
assert.match(gas, /\(subject === '英語' \|\| subject === '数学'\) && \['1','2','3'\]/);
assert.match(app, /id="adminStudentSearch"/);
assert.match(app, /function renderAdminStudentSearchResults/);
assert.match(app, /全在籍生徒から検索し、選ぶと管理者詳細を開きます/);
assert.match(gas, /directory:directory/);
assert.match(gas, /campuses:\['神領','大手町'\]/);
assert.match(gas, /grades:Array\.from\(new Set\(allActiveStudents\.map/);
assert.match(gas, /schools:schools/);
assert.match(app, /filterOptions\.campuses/);
assert.match(app, /filterOptions\.schools/);
assert.match(app, /data-campus="\$\{esc\(s\.filterCampus \|\| s\.campus\)\}"/);

console.log("teacher experience tests: five-subject assertions passed");
