from pathlib import Path

app_path=Path('app.js')
config_path=Path('config.js')
app=app_path.read_text()
config=config_path.read_text()

if 'fastRuntimeApiUrl' not in config:
    config=config.replace('  apiUrl: "https://script.google.com/macros/s/AKfycbz0z2FeM1jWUSs7LTzwi9N12kPoTmSTP_hRjTaf3wQlf5kX5hR_W9E37ON63L_dhbIZ/exec",', '  apiUrl: "https://script.google.com/macros/s/AKfycbz0z2FeM1jWUSs7LTzwi9N12kPoTmSTP_hRjTaf3wQlf5kX5hR_W9E37ON63L_dhbIZ/exec",\n  fastRuntimeApiUrl: "https://wisedgcgwaebtkprdhth.supabase.co/functions/v1/foresta-runtime-v3-staging",')

anchor='const PROGRESSION_CACHE_TTL_MS = 120000;\n'
insert='''const PROGRESSION_CACHE_TTL_MS = 120000;\nconst FAST_RUNTIME_ENABLED = new URLSearchParams(location.search).get("fastv3") === "1";\nconst FAST_RUNTIME_AUTH_ACTIONS = new Set(["studentLogin","staffLogin","resumeSession","logout","adminReauth","resumeAdminSession"]);\nconst FAST_RUNTIME_WRITE_ACTIONS = new Set(["saveLesson","updateLessonCorrection","saveSchoolPosition","saveRange","saveCt","studentCheckHomework","teacherCheckHomework","archiveHomework","restoreHomework","deleteHomework","saveTargets","saveComment","saveNote","markCommentRead"]);\nfunction apiEndpointFor(action) {\n  if (!FAST_RUNTIME_ENABLED || FAST_RUNTIME_AUTH_ACTIONS.has(action) || !CONFIG.fastRuntimeApiUrl) return CONFIG.apiUrl;\n  return CONFIG.fastRuntimeApiUrl;\n}\nfunction usingFastRuntimeFor(action) { return apiEndpointFor(action) === CONFIG.fastRuntimeApiUrl; }\n'''
if 'const FAST_RUNTIME_ENABLED' not in app:
    if anchor not in app: raise SystemExit('cache ttl anchor missing')
    app=app.replace(anchor,insert,1)

old='''async function api(action, payload = {}, { silent = false } = {}) {\n  if (CONFIG.apiUrl.includes("__GAS_")) throw new Error("公開APIの設定が完了していません。再読み込みしてください。");\n  const controller = new AbortController();\n  const timer = setTimeout(() => controller.abort(), CONFIG.requestTimeoutMs);\n  if (!silent) status("読み込み中…");\n  try {\n    const response = await fetch(CONFIG.apiUrl, {\n      method: "POST",\n      headers: { "Content-Type": "text/plain;charset=utf-8" },\n      body: JSON.stringify({ action, token: state.session?.token || "", adminToken: state.adminToken || "", ...payload }),\n      redirect: "follow",\n      signal: controller.signal,\n    });\n    const result = await response.json();\n    if (!response.ok || result.ok === false) throw new Error(result.message || "処理に失敗しました。");\n    status("");\n    return result;\n  } catch (error) {\n    status("");\n    if (error.name === "AbortError") throw new Error("通信がタイムアウトしました。もう一度お試しください。");\n    throw error;\n  } finally {\n    clearTimeout(timer);\n  }\n}\n'''
new='''async function api(action, payload = {}, { silent = false } = {}) {\n  if (CONFIG.apiUrl.includes("__GAS_")) throw new Error("公開APIの設定が完了していません。再読み込みしてください。");\n  const requestBody = { action, token: state.session?.token || "", adminToken: state.adminToken || "", ...payload };\n  const attempt = async (endpoint, fastAttempt = false) => {\n    const controller = new AbortController();\n    const timeoutMs = fastAttempt ? Math.min(CONFIG.requestTimeoutMs, 12000) : CONFIG.requestTimeoutMs;\n    const timer = setTimeout(() => controller.abort(), timeoutMs);\n    try {\n      const response = await fetch(endpoint, {\n        method: "POST",\n        headers: { "Content-Type": fastAttempt ? "application/json" : "text/plain;charset=utf-8" },\n        body: JSON.stringify(requestBody),\n        redirect: "follow",\n        signal: controller.signal,\n      });\n      const result = await response.json();\n      if (!response.ok || result.ok === false) throw new Error(result.message || "処理に失敗しました。");\n      return result;\n    } finally { clearTimeout(timer); }\n  };\n  if (!silent) status(FAST_RUNTIME_ENABLED && usingFastRuntimeFor(action) ? "高速保存中…" : "読み込み中…");\n  const endpoint = apiEndpointFor(action);\n  try {\n    const result = await attempt(endpoint, endpoint === CONFIG.fastRuntimeApiUrl);\n    status("");\n    return result;\n  } catch (error) {\n    if (endpoint === CONFIG.fastRuntimeApiUrl) {\n      try {\n        const fallback = await attempt(CONFIG.apiUrl, false);\n        status("");\n        return { ...fallback, _fastRuntimeFallback: true };\n      } catch (fallbackError) {\n        status("");\n        if (fallbackError.name === "AbortError") throw new Error("通信がタイムアウトしました。もう一度お試しください。");\n        throw fallbackError;\n      }\n    }\n    status("");\n    if (error.name === "AbortError") throw new Error("通信がタイムアウトしました。もう一度お試しください。");\n    throw error;\n  }\n}\n'''
if old not in app: raise SystemExit('api function anchor missing')
app=app.replace(old,new,1)

old='''    await api(correcting ? "updateLessonCorrection" : "saveLesson", { studentId: options.studentId, subject: options.subject, lessonId: options.lessonId, teacherId: options.teacherId, unitIds: options.unitIds, homeworkByUnit, idempotencyKey: options.idempotencyKey, outsideRangeOverrideUnitIds: options.outsideRangeOverrideUnitIds || [] });\n    invalidateProgressionCache(options);\n    delete state.teacherStudentCache[String(options.studentId)];\n    delete $("modal").dataset.refreshTeacher;\n    closeModal();\n    status(`${correcting ? "訂正内容を" : ""}保存しました。画面を更新しています…`);\n    await openView("selected");\n'''
new='''    const saveResult = await api(correcting ? "updateLessonCorrection" : "saveLesson", { studentId: options.studentId, subject: options.subject, lessonId: options.lessonId, teacherId: options.teacherId, unitIds: options.unitIds, homeworkByUnit, idempotencyKey: options.idempotencyKey, outsideRangeOverrideUnitIds: options.outsideRangeOverrideUnitIds || [] });\n    invalidateProgressionCache(options);\n    delete state.teacherStudentCache[String(options.studentId)];\n    delete $("modal").dataset.refreshTeacher;\n    closeModal();\n    if (FAST_RUNTIME_ENABLED && saveResult?.queued && !saveResult?._fastRuntimeFallback) {\n      status(`${correcting ? "訂正内容を" : ""}保存しました（高速保存）。同期はバックグラウンドで続きます。`);\n      setTimeout(() => {\n        delete state.teacherStudentCache[String(options.studentId)];\n        if (state.activeView === "selected" && String(state.activeStudentId) === String(options.studentId)) openView("selected").catch(() => {});\n      }, 1800);\n      return;\n    }\n    status(`${correcting ? "訂正内容を" : ""}保存しました。画面を更新しています…`);\n    await openView("selected");\n'''
if old not in app: raise SystemExit('saveLesson refresh anchor missing')
app=app.replace(old,new,1)

# Put a small marker in the shell only while the explicit staging flag is active.
old='''  $("userMeta").textContent = `${state.role === "student" ? "生徒" : state.role === "teacher" ? "講師" : "管理者"} / ${state.session?.campus || "—"}${state.session?.grade ? ` / ${state.session.grade}` : ""}${state.session?.school ? ` / ${state.session.school}` : ""}`;'''
new='''  $("userMeta").textContent = `${state.role === "student" ? "生徒" : state.role === "teacher" ? "講師" : "管理者"} / ${state.session?.campus || "—"}${state.session?.grade ? ` / ${state.session.grade}` : ""}${state.session?.school ? ` / ${state.session.school}` : ""}${FAST_RUNTIME_ENABLED ? " / ⚡V3高速試験" : ""}`;'''
if old in app: app=app.replace(old,new,1)

app_path.write_text(app)
config_path.write_text(config)
