from pathlib import Path

p=Path('app.js')
s=p.read_text()

old='''const FAST_RUNTIME_ENABLED = new URLSearchParams(location.search).get("fastv3") === "1";\nconst FAST_RUNTIME_AUTH_ACTIONS = new Set(["studentLogin","staffLogin","resumeSession","logout","adminReauth","resumeAdminSession"]);\nconst FAST_RUNTIME_WRITE_ACTIONS = new Set(["saveLesson","updateLessonCorrection","saveSchoolPosition","saveRange","saveCt","studentCheckHomework","teacherCheckHomework","archiveHomework","restoreHomework","deleteHomework","saveTargets","saveComment","saveNote","markCommentRead"]);\nfunction apiEndpointFor(action) {\n  if (!FAST_RUNTIME_ENABLED || FAST_RUNTIME_AUTH_ACTIONS.has(action) || !CONFIG.fastRuntimeApiUrl) return CONFIG.apiUrl;\n  return CONFIG.fastRuntimeApiUrl;\n}\nfunction usingFastRuntimeFor(action) { return apiEndpointFor(action) === CONFIG.fastRuntimeApiUrl; }\n'''
new='''const FAST_RUNTIME_ENABLED = new URLSearchParams(location.search).get("fastv3") === "1";\nconst FAST_RUNTIME_AUTH_ACTIONS = new Set(["studentLogin","staffLogin","resumeSession","logout","adminReauth","resumeAdminSession"]);\nconst FAST_RUNTIME_READ_ACTIONS = new Set(["getStudentDashboard","getProgression","searchStudents","getTeacherToday","getHomeworkArchive"]);\nconst FAST_RUNTIME_WRITE_ACTIONS = new Set(["saveLesson","updateLessonCorrection","saveSchoolPosition","saveRange","saveCt","studentCheckHomework","teacherCheckHomework"]);\nconst FAST_LOCAL_READ_ACTIONS = new Set(["getStudentDashboard","getProgression"]);\nconst FAST_LOCAL_CACHE_PREFIX = "forestaFastV3:";\nfunction apiEndpointFor(action) {\n  if (!FAST_RUNTIME_ENABLED || FAST_RUNTIME_AUTH_ACTIONS.has(action) || !CONFIG.fastRuntimeApiUrl) return CONFIG.apiUrl;\n  if (!FAST_RUNTIME_READ_ACTIONS.has(action) && !FAST_RUNTIME_WRITE_ACTIONS.has(action)) return CONFIG.apiUrl;\n  return CONFIG.fastRuntimeApiUrl;\n}\nfunction usingFastRuntimeFor(action) { return apiEndpointFor(action) === CONFIG.fastRuntimeApiUrl; }\nfunction fastLocalCacheKey(action, payload = {}) {\n  const studentId = payload.studentId || state.activeStudentId || state.session?.studentId || state.session?.loginId || "self";\n  return `${FAST_LOCAL_CACHE_PREFIX}${state.role}|${state.session?.loginId || ""}|${studentId}|${action}|${payload.subject || ""}|${payload.mode || ""}`;\n}\nfunction readFastLocalCache(action, payload = {}) {\n  if (!FAST_RUNTIME_ENABLED || !FAST_LOCAL_READ_ACTIONS.has(action)) return null;\n  try {\n    const raw = sessionStorage.getItem(fastLocalCacheKey(action, payload));\n    if (!raw) return null;\n    const parsed = JSON.parse(raw);\n    if (!parsed?.data || Date.now() - Number(parsed.savedAt || 0) > 6 * 60 * 60 * 1000) return null;\n    return parsed.data;\n  } catch (_) { return null; }\n}\nfunction writeFastLocalCache(action, payload, data) {\n  if (!FAST_RUNTIME_ENABLED || !FAST_LOCAL_READ_ACTIONS.has(action) || !data) return;\n  try { sessionStorage.setItem(fastLocalCacheKey(action, payload), JSON.stringify({ savedAt: Date.now(), data })); } catch (_) {}\n}\nfunction scheduleFastRefreshAfterWrite(action, requestBody) {\n  if (!FAST_RUNTIME_ENABLED || !FAST_RUNTIME_WRITE_ACTIONS.has(action)) return;\n  const studentId = requestBody.studentId || state.activeStudentId || state.session?.studentId || "";\n  setTimeout(() => {\n    const dashboardPayload = state.role === "student" ? {} : (studentId ? { studentId } : {});\n    api("getStudentDashboard", dashboardPayload, { silent: true, forceNetwork: true }).catch(() => {});\n    if (studentId && requestBody.subject && ["saveLesson","updateLessonCorrection","saveSchoolPosition","saveCt"].includes(action)) {\n      api("getProgression", { studentId, subject: requestBody.subject, mode: "lesson" }, { silent: true, forceNetwork: true }).catch(() => {});\n    }\n  }, 2500);\n}\n'''
if old not in s: raise SystemExit('fast runtime block anchor missing')
s=s.replace(old,new,1)

old='''async function api(action, payload = {}, { silent = false } = {}) {\n  if (CONFIG.apiUrl.includes("__GAS_")) throw new Error("公開APIの設定が完了していません。再読み込みしてください。");\n  const requestBody = { action, token: state.session?.token || "", adminToken: state.adminToken || "", ...payload };'''
new='''async function api(action, payload = {}, { silent = false, forceNetwork = false } = {}) {\n  if (CONFIG.apiUrl.includes("__GAS_")) throw new Error("公開APIの設定が完了していません。再読み込みしてください。");\n  if (!forceNetwork) {\n    const local = readFastLocalCache(action, payload);\n    if (local) {\n      queueMicrotask(() => api(action, payload, { silent: true, forceNetwork: true }).catch(() => {}));\n      return { ...local, _fastLocalCache: true };\n    }\n  }\n  const requestBody = { action, token: state.session?.token || "", adminToken: state.adminToken || "", ...payload };'''
if old not in s: raise SystemExit('api signature anchor missing')
s=s.replace(old,new,1)

old='''    const result = await attempt(endpoint, endpoint === CONFIG.fastRuntimeApiUrl);\n    status("");\n    return result;'''
new='''    const result = await attempt(endpoint, endpoint === CONFIG.fastRuntimeApiUrl);\n    writeFastLocalCache(action, payload, result);\n    if (result?.queued) scheduleFastRefreshAfterWrite(action, requestBody);\n    status("");\n    return result;'''
if old not in s: raise SystemExit('api success anchor missing')
s=s.replace(old,new,1)

old='''        const fallback = await attempt(CONFIG.apiUrl, false);\n        status("");\n        return { ...fallback, _fastRuntimeFallback: true };'''
new='''        const fallback = await attempt(CONFIG.apiUrl, false);\n        writeFastLocalCache(action, payload, fallback);\n        status("");\n        return { ...fallback, _fastRuntimeFallback: true };'''
if old not in s: raise SystemExit('fallback anchor missing')
s=s.replace(old,new,1)

old='''    if (FAST_RUNTIME_ENABLED && saveResult?.queued && !saveResult?._fastRuntimeFallback) {\n      status(`${correcting ? "訂正内容を" : ""}保存しました（高速保存）。同期はバックグラウンドで続きます。`);\n      setTimeout(() => {\n        delete state.teacherStudentCache[String(options.studentId)];\n        if (state.activeView === "selected" && String(state.activeStudentId) === String(options.studentId)) openView("selected").catch(() => {});\n      }, 1800);\n      return;\n    }'''
new='''    if (FAST_RUNTIME_ENABLED && saveResult?.queued && !saveResult?._fastRuntimeFallback) {\n      status(`${correcting ? "訂正内容を" : ""}保存しました（高速保存）。画面を待たせず、同期はバックグラウンドで続きます。`);\n      return;\n    }'''
if old not in s: raise SystemExit('save queued anchor missing')
s=s.replace(old,new,1)

old='''      await api("teacherCheckHomework", { homeworkId: input.dataset.id, checked: nextChecked });\n      if (state.activeStudentId) {\n        delete state.teacherStudentCache[String(state.activeStudentId)];\n        await renderTeacherStudent(state.activeStudentId, { force: true });\n      }'''
new='''      const result = await api("teacherCheckHomework", { studentId: state.activeStudentId, homeworkId: input.dataset.id, checked: nextChecked });\n      if (FAST_RUNTIME_ENABLED && result?.queued && !result?._fastRuntimeFallback) {\n        input.disabled = false;\n        status("講師チェックを保存しました（高速保存）。");\n        return;\n      }\n      if (state.activeStudentId) {\n        delete state.teacherStudentCache[String(state.activeStudentId)];\n        await renderTeacherStudent(state.activeStudentId, { force: true });\n      }'''
if old not in s: raise SystemExit('teacher homework anchor missing')
s=s.replace(old,new,1)

p.write_text(s)
